### ISSUE TITLE
The "tw" command is not case-sensitive

### ISSUE THREAD

**Issue by luizfernandonb** [yshrsmz/omnitweety#26]
For me it is a good idea to activate Omnitweety with "TW", "tW", "Tw", etc.
And if the user doesn't like it, just disable it in the options to only use "tw" to call Omnitweety

**Comment by yshrsmz** [comment]
Thanks for your suggestion, but it looks like Chrome Extension can only have one single keyword

https://developer.chrome.com/docs/extensions/reference/omnibox/

**Comment by luizfernandonb** [comment]
> Thanks for your suggestion, but it looks like Chrome Extension can only have one single keyword
> 
> https://developer.chrome.com/docs/extensions/reference/omnibox/

Oh, ok
